version: "3.8"
services:
  bdpz-es-api:
    depends_on:
      - elasticsearch
    build: .
    restart: on-failure
    ports:
      - 8090:8090
    environment:
      - ELASTICSEARCH_HOST=bdpz-elasticsearch-elasticsearch-1
      - ELASTICSEARCH_PORT=9200
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    restart: unless-stopped
    environment:
      - DISCOVERY_TYPE=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  esdata:
networks:
  bdpz: